CREATE TABLE [dbo].[dados_sistema](
	 ID INT NULL
	,NOME VARCHAR(50) NULL
	,SOBRENOME VARCHAR(50) NULL
	,LOCALIDADE VARCHAR(50) NULL
	,GENERO VARCHAR(50) NULL
	,EMAIL VARCHAR(50) NULL
	,UNIVERSIDADE VARCHAR(50) NULL
	,MODELO_CARRO VARCHAR(50) NULL

)ON [PRIMARY]
GO


